sudo: false
language: ruby
rvm:
  - 2.3.1
before_install: gem install bundler -v 1.16.0.pre.3

before_script:
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  
 after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  
 env:
  global:
    - CC_TEST_REPORTER_ID=ec4fd9d5fdb3f0b610069686575e97d79b4b3c03f3102517e6145076b5ee22d5
